site_url: ''
site_name: webЯcade Docs
repo_url: https://github.com/webrcade/webrcade-docs
edit_uri: edit/main/docs/
dev_addr: '127.0.0.1:8080'
copyright: "&copy; Copyright webЯcade 2022"

nav:
  - About: index.md
  - User Guide: userguide/index.md
  - Platforms:
    - Overview: platforms/index.md
    - Windows (PC):
      - Overview: platforms/windows/index.md
      - Gamepads: platforms/windows/gamepads.md
    - macOS (Mac):
      - Overview: platforms/osx/index.md
      - Gamepads: platforms/osx/gamepads.md
    - iOS:
      - Overview: platforms/ios/index.md
      - Gamepads: platforms/ios/gamepads.md
    - Android:
      - Overview: platforms/android/index.md
      - Gamepads: platforms/android/gamepads.md
    - Xbox Series X|S:
      - Overview: platforms/xbox/index.md
  - Applications:
    - Overview: apps/index.md
    - Emulators:
      - Overview: apps/emulators/index.md
      - Arcade: apps/emulators/arcade/index.md
      - Atari:
        - 2600: apps/emulators/2600/index.md
        - 7800: apps/emulators/7800/index.md
        - Lynx: apps/emulators/lynx/index.md
      - Bandai:
        - WonderSwan: apps/emulators/ws/index.md
      - NEC:
        - PC Engine (TurboGrafx-16): apps/emulators/pce/index.md
        - PC Engine CD (TurboGrafx-CD): apps/emulators/pcecd/index.md
        - SuperGrafx: apps/emulators/sgx/index.md
      - Nintendo:
        - N64 (Experimental): apps/emulators/n64/index.md
        - NES: apps/emulators/nes/index.md
        - SNES: apps/emulators/snes/index.md
        - Game Boy: apps/emulators/gb/index.md
        - Game Boy Color: apps/emulators/gbc/index.md
        - Game Boy Advance: apps/emulators/gba/index.md
        - Virtual Boy: apps/emulators/vb/index.md
      - Sega:
        - SG-1000: apps/emulators/sg1000/index.md
        - Master System: apps/emulators/mastersystem/index.md
        - Genesis: apps/emulators/genesis/index.md
        - Sega CD: apps/emulators/segacd/index.md
        - Game Gear: apps/emulators/gamegear/index.md
      - SNK:
        - Neo Geo: apps/emulators/neogeo/index.md
        - Neo Geo Pocket: apps/emulators/ngp/index.md
      - Sony:
        - PlayStation: apps/emulators/psx/index.md
    - Engines:
      - Overview: apps/engines/index.md
      - Classic Doom: apps/engines/doom/index.md
  - Feeds:
    - Overview: feeds/index.md
    - Format: feeds/format.md
    - Tutorial: feeds/tutorial.md
    - Resources:
      - Overview: feeds/resources/index.md
      - Dropbox: feeds/resources/dropbox.md
      - Imgur: feeds/resources/imgur.md
      - Internet Archive: feeds/resources/inetarchive.md
      - Pastebin: feeds/resources/pastebin.md
      - Snippet.host: feeds/resources/snippet.md
      - TinyURL: feeds/resources/tinyurl.md
  - Editor:
    - Overview: editor/index.md
    - Sidebar: editor/sidebar.md
    - Feed Workspace:
      - Overview: editor/workspace/index.md
      - Tabs:
        - Categories Tab: editor/workspace/categoriestab.md
        - Items Tab: editor/workspace/itemstab.md
      - Settings Dialog: editor/workspace/settings.md
      - Adding Items: editor/workspace/addingitems.md
    - Editors:
      - Feed Editor: editor/dialogs/feed-dialog.md
      - Category Editor: editor/dialogs/category-dialog.md
      - Item Editor: editor/dialogs/item-dialog.md
    - General:
      - Drag and Drop: editor/draganddrop.md
      - Thumbnails: editor/thumbnails.md
  - Stand-alone: standalone/index.md
  - Cloud Storage: storage/index.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/C4gXN2HJAv
    - icon: fontawesome/brands/github
      link: https://github.com/webrcade
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCuoR0CBb9XCnxurYg-HfCvQ
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/webrcade
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/webrcade


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

theme:
  copyright: Copyright &copy; 2022 webЯcade
  name: 'material'
  logo: assets/images/webrcade-logo.svg
  palette:
    - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.expand
    #- navigation.indexes







